db:
  type: POSTGRES
  config:
    user: postgres
    host: 47.109.34.74
    database: example
    password: zhaojunlike
    port: 5432

debugger: true
onlineTable: true
tables:
  - calendars
  - socialmedia_discord_states
enable: backend-pg

template:
  bsc-backend:
    out: output
    ext: ts
    path:
      Bean.controller.t:
        base: controllers
      Bean.service.t:
        base: services
      Bean.schema.t:
        base: schemas
  backend-pg:
    out: output
    ext: ts
    path:
      Bean.controller.t:
        base: controllers
      Bean.service.t:
        base: services
      Bean.entity.t:
        base: schemas
      Bean.dto.t:
        base: dto

output: