db:
  type: POSTGRES
  config:
    user: tsdbadmin
    host: xxymlqow06.bn122svyo5.tsdb.cloud.timescale.com
    database: tsdb
    password: bjjb8dvy5yi7q0h9
    port: 32260
#    user: postgres
#    host: 47.109.34.74
#    database: verytech_web
#    password: zhaojunlike
#    port: 5432
#
#
debugger: true
onlineTable: true
tables:
  - calendars
  - socialmedia_discord_states
enable: backend-pg

template:
  bsc-backend:
    out: output
    ext: ts
    path:
      Bean.controller.t:
        base: controllers
      Bean.service.t:
        base: services
      Bean.schema.t:
        base: schemas
  backend-pg:
    out: output
    ext: ts
    path:
      Bean.controller.t:
        base: controllers
      Bean.service.t:
        base: services
      Bean.entity.t:
        base: schemas
      Bean.dto.t:
        base: dto
#      Bean.schema.t:
#        base: ts-schema
#      Bean.t:
#        base: api
#      Bean.vue.t:
#        base: vue

output: